services:
  db:
    image: postgres:15-alpine
    container_name: bookify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bookify_db
      - POSTGRES_USER=bookify_user
      - POSTGRES_PASSWORD=bookify_secure_pass
    expose:
      - "5432"

  web:
    build: .
    container_name: bookify_backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: bookify_proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web

volumes:
  postgres_data: